#!/usr/bin/env python3
"""Generate tool-specific agent files from the canonical definitions in .agents/.

Canonical sources (edit these):
  .agents/agents/*.md     subagents (frontmatter: name, description, access)
  .agents/skills/*/       skills (read natively by GitHub Copilot and Codex)

Generated outputs (do not edit by hand):
  .claude/agents/*.md        Claude Code subagents
  .claude/skills/*/          Claude Code skills (copy of .agents/skills)
  .github/agents/*.agent.md  GitHub Copilot custom agents (subagents)
  .codex/agents/*.toml       Codex custom agents

Usage:
  python3 tools/sync_agents.py          write generated files
  python3 tools/sync_agents.py --check  exit 1 if generated files are out of date
"""

import argparse
import json
import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "GENERATED by tools/sync_agents.py"
NOTE = "%s from %%s — edit the source and re-run the script." % MARKER

ACCESS = {
    "read-only": {
        "claude": "Read, Glob, Grep, Bash",
        "copilot": ["read", "search", "execute"],
        "codex": "read-only",
    },
    "report": {
        "claude": "Read, Write, Glob, Grep, Bash",
        "copilot": ["read", "edit", "search", "execute"],
        "codex": "workspace-write",
    },
    "write": {
        "claude": "Read, Write, Edit, Glob, Grep, Bash",
        "copilot": ["read", "edit", "search", "execute", "todo"],
        "codex": "workspace-write",
    },
}


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def parse_agent(path):
    text = read(path)
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        sys.exit("error: %s has no frontmatter" % path)
    meta = {}
    for line in m.group(1).splitlines():
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip().strip("\"'")
    for field in ("name", "description", "access"):
        if not meta.get(field):
            sys.exit("error: %s: missing '%s'" % (path, field))
    if meta["access"] not in ACCESS:
        sys.exit("error: %s: access must be one of %s" % (path, ", ".join(ACCESS)))
    meta["body"] = m.group(2).strip() + "\n"
    meta["source"] = os.path.relpath(path, ROOT)
    return meta


def render_agents(agent):
    tools = ACCESS[agent["access"]]
    note = NOTE % agent["source"]
    name, desc, body = agent["name"], agent["description"], agent["body"]
    claude = (
        "---\nname: %s\ndescription: %s\ntools: %s\nmodel: inherit\n---\n<!-- %s -->\n\n%s"
        % (name, json.dumps(desc, ensure_ascii=False), tools["claude"], note, body)
    )
    copilot = (
        "---\nname: %s\ndescription: %s\ntools: %s\nuser-invocable: false\n---\n<!-- %s -->\n\n%s"
        % (name, json.dumps(desc, ensure_ascii=False), json.dumps(tools["copilot"]), note, body)
    )
    if "'''" in body:
        sys.exit("error: %s: body must not contain '''" % agent["source"])
    codex = (
        "# %s\nname = %s\ndescription = %s\nsandbox_mode = %s\ndeveloper_instructions = '''\n%s'''\n"
        % (note, json.dumps(name), json.dumps(desc, ensure_ascii=False), json.dumps(tools["codex"]), body)
    )
    return {
        os.path.join(".claude", "agents", name + ".md"): claude,
        os.path.join(".github", "agents", name + ".agent.md"): copilot,
        os.path.join(".codex", "agents", name + ".toml"): codex,
    }


def render_skills():
    out = {}
    src_root = os.path.join(ROOT, ".agents", "skills")
    for dirpath, _, filenames in os.walk(src_root):
        for fn in sorted(filenames):
            src = os.path.join(dirpath, fn)
            rel = os.path.relpath(src, src_root)
            dest = os.path.join(".claude", "skills", rel)
            if fn == "SKILL.md":
                text = read(src)
                note = "<!-- %s -->\n" % (NOTE % os.path.relpath(src, ROOT))
                m = re.match(r"^(---\n.*?\n---\n)(.*)$", text, re.S)
                out[dest] = (m.group(1) + note + m.group(2)) if m else note + text
            else:
                out[dest] = ("copy", src)
    return out


def expected():
    files = {}
    agents_dir = os.path.join(ROOT, ".agents", "agents")
    for fn in sorted(os.listdir(agents_dir)):
        if fn.endswith(".md") and fn != "README.md":
            files.update(render_agents(parse_agent(os.path.join(agents_dir, fn))))
    files.update(render_skills())
    return files


def generated_on_disk():
    """Existing files in output dirs that carry the generated marker."""
    found = set()
    for sub in (".claude/agents", ".claude/skills", ".github/agents", ".codex/agents"):
        base = os.path.join(ROOT, sub)
        for dirpath, _, filenames in os.walk(base):
            for fn in filenames:
                path = os.path.join(dirpath, fn)
                rel = os.path.relpath(path, ROOT)
                if rel.startswith(os.path.join(".claude", "skills")):
                    found.add(rel)  # the whole .claude/skills tree is generated
                elif MARKER in read(path):
                    found.add(rel)
    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="only verify, don't write")
    args = parser.parse_args()

    files = expected()
    stale = sorted(generated_on_disk() - set(files))
    changed = []
    for rel, content in sorted(files.items()):
        path = os.path.join(ROOT, rel)
        if isinstance(content, tuple):
            new = open(content[1], "rb").read()
            old = open(path, "rb").read() if os.path.exists(path) else None
        else:
            new = content.encode("utf-8")
            old = open(path, "rb").read() if os.path.exists(path) else None
        if old != new:
            changed.append(rel)
            if not args.check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "wb") as f:
                    f.write(new)

    if not args.check:
        for rel in stale:
            os.remove(os.path.join(ROOT, rel))
        # prune empty dirs left in .claude/skills
        for dirpath, dirnames, filenames in sorted(os.walk(os.path.join(ROOT, ".claude", "skills")), reverse=True):
            if not dirnames and not filenames and dirpath != os.path.join(ROOT, ".claude", "skills"):
                shutil.rmtree(dirpath)

    for rel in changed:
        print(("OUTDATED " if args.check else "wrote    ") + rel)
    for rel in stale:
        print(("STALE    " if args.check else "removed  ") + rel)
    if args.check and (changed or stale):
        print("\nGenerated agent files are out of date. Run: python3 tools/sync_agents.py")
        return 1
    if not changed and not stale:
        print("all generated agent files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
