#!/usr/bin/env python3
"""LLM Wiki helper CLI. Standard library only (Python 3.8+). Works on Windows, macOS, Linux.

Everyday:
  status                 Overview: pages, pending sources, recent log, linked wikis, health
  search <query>         Rank wiki pages by relevance
  index [--check]        Regenerate wiki/index.md from page frontmatter
  lint [--quick]         Mechanical health checks (exit 1 on errors)
  pending                Raw files not yet ingested (no source page with `raw:` pointing to them)
  log [-n N]             Show recent log entries
  log add OP TITLE -m …  Append a well-formed log entry

Cross-wiki:
  wikis                  Linked wikis (auto-discovered siblings + wiki.config.yaml)
  xlinks                 Verify [[wiki-id:slug]] references

Framework:
  sync [--check]         Regenerate tool-specific agent files from .agents/
  upgrade [--from PATH]  Update framework files from the template repo
  new <dir> [...]        Create a new wiki from this framework
  init [...]             Turn a fresh "Use this template" copy into a wiki, in place

Use --root to operate on another wiki (default: the repo containing this script).
"""

import argparse
import datetime as dt
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter, defaultdict

DEFAULT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_FRAMEWORK_REPO = "https://github.com/revuls/llm-wiki.git"
LOG_OPS = ("setup", "ingest", "query", "lint", "link", "refactor", "schema", "upgrade")
REQUIRED_FIELDS = ("title", "type", "updated")
VALID_TYPES = {"source", "entity", "concept", "topic", "analysis", "overview", "meta"}
NEEDS_SOURCES = {"entity", "concept", "topic", "analysis"}
SECTION_ORDER = ["overview", "topics", "entities", "concepts", "analyses"]
SECTION_LAST = ["sources", "meta"]
DEFAULT_CATEGORIES = ["sources", "entities", "concepts", "topics", "analyses"]

WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]")
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
LOG_ENTRY_RE = re.compile(r"^## \[\d{4}-\d{2}-\d{2}\] (%s) \| .+" % "|".join(LOG_OPS))
GENERATED = "GENERATED by tools/wiki.py"


# --------------------------------------------------------------------------- small utils

def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def write(path, text):
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def posix(path):
    return path.replace(os.sep, "/")


def today():
    return dt.date.today().isoformat()


def git(root, *args, check=False):
    if not shutil.which("git"):
        return None
    r = subprocess.run(["git", "-C", root] + list(args), capture_output=True, text=True)
    if check and r.returncode != 0:
        sys.exit("error: git %s failed: %s" % (" ".join(args), r.stderr.strip()))
    return r.stdout.strip() if r.returncode == 0 else None


# --------------------------------------------------------------------------- yaml subset

def parse_scalar(value):
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        return [parse_scalar(v) for v in inner.split(",")] if inner else []
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    if value.lower() in ("true", "false"):
        return value.lower() == "true"
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def strip_comment(line):
    in_quote = None
    for i, ch in enumerate(line):
        if ch in "\"'":
            in_quote = None if in_quote == ch else (in_quote or ch)
        elif ch == "#" and not in_quote and (i == 0 or line[i - 1].isspace()):
            return line[:i].rstrip()
    return line.rstrip()


def load_yaml(text):
    """Minimal YAML subset: nested maps, lists of scalars/maps, folded scalars, inline lists."""
    try:
        import yaml  # type: ignore
        return yaml.safe_load(text) or {}
    except ImportError:
        pass
    lines = [strip_comment(l) for l in text.splitlines()]
    lines = [l for l in lines if l.strip()]
    pos = 0

    def indent(l):
        return len(l) - len(l.lstrip(" "))

    def parse_block(level):
        nonlocal pos
        if pos < len(lines) and lines[pos].lstrip().startswith("- "):
            result = []
            while pos < len(lines) and indent(lines[pos]) == level and lines[pos].lstrip().startswith("- "):
                item = lines[pos].lstrip()[2:]
                if re.match(r"^[\w-]+:( |$)", item):
                    lines[pos] = " " * (level + 2) + item
                    result.append(parse_block(level + 2))
                else:
                    result.append(parse_scalar(item))
                    pos += 1
            return result
        result = {}
        while pos < len(lines) and indent(lines[pos]) == level:
            key, _, rest = lines[pos].strip().partition(":")
            rest = rest.strip()
            pos += 1
            if rest in (">", "|", ">-", "|-"):
                parts = []
                while pos < len(lines) and indent(lines[pos]) > level:
                    parts.append(lines[pos].strip())
                    pos += 1
                result[key] = " ".join(parts)
            elif rest:
                result[key] = parse_scalar(rest)
            elif pos < len(lines) and indent(lines[pos]) > level:
                result[key] = parse_block(indent(lines[pos]))
            elif pos < len(lines) and indent(lines[pos]) == level and lines[pos].lstrip().startswith("- "):
                result[key] = parse_block(level)
            else:
                result[key] = None
        return result

    return parse_block(0) if lines else {}


def split_frontmatter(text):
    if not text.startswith("---"):
        return None, text
    end = text.find("\n---", 3)
    if end == -1:
        return None, text
    raw = text[3:end].strip("\n")
    body = text[end + 4:].lstrip("\n")
    try:
        fm = load_yaml(raw)
    except Exception:
        fm = {"__invalid__": True}
    return (fm if isinstance(fm, dict) else {"__invalid__": True}), body


def load_config(root):
    path = os.path.join(root, "wiki.config.yaml")
    return (load_yaml(read(path)) or {}) if os.path.exists(path) else {}


# --------------------------------------------------------------------------- model

def clean_for_links(text):
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    return re.sub(r"`[^`\n]*`", "", text)


class Page:
    def __init__(self, root, path):
        self.path = path
        self.rel = posix(os.path.relpath(path, root))
        self.slug = os.path.splitext(os.path.basename(path))[0]
        self.text = read(path)
        self.fm, self.body = split_frontmatter(self.text)
        links = [l.strip() for l in WIKILINK_RE.findall(clean_for_links(self.body))]
        self.links = [l for l in links if ":" not in l]
        self.xlinks = [l for l in links if ":" in l]
        parts = self.rel.split("/")
        self.section = "overview" if len(parts) == 2 else ("meta" if parts[1] == "_meta" else parts[1])

    def get(self, key, default=None):
        return (self.fm or {}).get(key, default)

    @property
    def title(self):
        if self.get("title"):
            return str(self.get("title"))
        m = re.search(r"^# (.+)$", self.body, re.M)
        return m.group(1).strip() if m else self.slug

    @property
    def type(self):
        return self.get("type")

    @property
    def special(self):
        return self.rel in ("wiki/index.md", "wiki/log.md")

    @property
    def generated_index(self):
        return self.rel.startswith("wiki/_meta/index-")

    @property
    def source_slugs(self):
        return sorted(set(l for l in self.links if l.startswith("src-")))


class Wiki:
    def __init__(self, root):
        self.root = os.path.abspath(root)
        self.wiki_dir = os.path.join(self.root, "wiki")
        self.raw_dir = os.path.join(self.root, "raw")
        if not os.path.isdir(self.wiki_dir):
            sys.exit("error: no wiki/ directory under %s" % self.root)
        self.config = load_config(self.root)
        self.pages = []
        for dirpath, dirnames, filenames in os.walk(self.wiki_dir):
            dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
            for fn in sorted(filenames):
                if fn.endswith(".md"):
                    self.pages.append(Page(self.root, os.path.join(dirpath, fn)))
        self.by_slug = defaultdict(list)
        for p in self.pages:
            self.by_slug[p.slug].append(p)

    @property
    def id(self):
        return self.config.get("id")

    def page(self, slug):
        found = self.by_slug.get(slug)
        return found[0] if found else None

    def content_pages(self):
        return [p for p in self.pages if not p.special and not p.generated_index]

    def inbound(self):
        inbound = defaultdict(set)
        for p in self.content_pages():
            for target in p.links:
                inbound[target].add(p.slug)
        return inbound


# --------------------------------------------------------------------------- linked wikis

def discover_wikis(wiki):
    """Return ({id: info}, problems). Sources: sibling folders + linked_wikis in config."""
    found, problems = {}, []
    exclude = set(wiki.config.get("exclude_wikis") or [])

    def add(path, origin, fallback=None):
        path = os.path.normpath(path)
        available = os.path.isdir(os.path.join(path, "wiki"))
        cfg = load_config(path) if available else {}
        if cfg.get("template"):
            return
        info = dict(fallback or {})
        info.update({k: v for k, v in cfg.items() if k in ("id", "name", "description", "scope")})
        wid = info.get("id")
        if not wid or wid == wiki.id or wid in exclude:
            return
        if wid in found and os.path.normpath(found[wid]["path"]) != path:
            problems.append("duplicate wiki id '%s': %s and %s" % (wid, found[wid]["path"], path))
            return
        scope = info.get("scope")
        if isinstance(scope, dict):
            scope = "; ".join(str(s) for s in (scope.get("in") or []))
        info.update({"path": path, "origin": origin, "available": available, "scope": scope or ""})
        found[wid] = info

    if wiki.config.get("link_siblings", True):
        parent = os.path.dirname(wiki.root)
        for name in sorted(os.listdir(parent)):
            p = os.path.join(parent, name)
            if p != wiki.root and os.path.isfile(os.path.join(p, "wiki.config.yaml")):
                add(p, "sibling")
    for entry in wiki.config.get("linked_wikis") or []:
        if isinstance(entry, dict) and entry.get("path"):
            add(os.path.join(wiki.root, str(entry["path"])), "config", entry)
    return found, problems


# --------------------------------------------------------------------------- index

def section_title(key):
    return {"overview": "Overview", "meta": "Meta"}.get(key, key.replace("-", " ").title())


def index_entry(p):
    summary = str(p.get("summary") or "_(no summary)_")
    updated = p.get("updated") or "?"
    if p.type == "source":
        return "- [[%s]] — %s (updated %s)" % (p.slug, summary, updated)
    n = len(p.source_slugs)
    if p.type in NEEDS_SOURCES:
        return "- [[%s]] — %s (%d source%s, updated %s)" % (p.slug, summary, n, "" if n == 1 else "s", updated)
    return "- [[%s]] — %s" % (p.slug, summary)


def build_index(wiki):
    """Return {relative path: content} for wiki/index.md and any split index pages."""
    sections = defaultdict(list)
    for p in wiki.content_pages():
        sections[p.section].append(p)
    others = sorted(k for k in sections if k not in SECTION_ORDER + SECTION_LAST)
    order = [k for k in SECTION_ORDER + others + SECTION_LAST if k in sections or k in DEFAULT_CATEGORIES]
    for key, pages in sections.items():
        if key == "sources":
            pages.sort(key=lambda p: p.slug, reverse=True)
        else:
            pages.sort(key=lambda p: (p.section != "overview", p.title.lower()))

    total = sum(len(v) for k, v in sections.items() if k not in ("overview", "meta"))
    split_after = int((wiki.config.get("index") or {}).get("split_after") or 300)
    split = total > split_after
    head = ("# Index\n\n<!-- %s index — do not edit by hand. Set `summary:` in each page's "
            "frontmatter and run `python3 tools/wiki.py index`. -->\n\n"
            "Catalog of every page in this wiki (%d content pages). Read it first when answering a question.\n"
            % (GENERATED, total))
    out, parts = {}, [head]
    for key in order:
        pages = sections.get(key, [])
        parts.append("\n## %s\n" % section_title(key))
        if split and key not in ("overview", "meta"):
            slug = "index-" + key
            parts.append("- [[%s]] — %s (%d pages)\n" % (slug, section_title(key), len(pages)))
            updated = max([str(p.get("updated") or "") for p in pages] or [""]) or today()
            out["wiki/_meta/%s.md" % slug] = (
                "---\ntitle: Index — %s\ntype: meta\nsummary: Catalog of %s pages (generated).\nupdated: %s\n---\n\n"
                "# Index — %s\n\n<!-- %s index -->\n\n%s\n"
                % (section_title(key), key, updated, section_title(key), GENERATED,
                   "\n".join(index_entry(p) for p in pages) or "_None yet._"))
        else:
            parts.append(("\n".join(index_entry(p) for p in pages) or "_None yet._") + "\n")
    out["wiki/index.md"] = "".join(parts)
    return out


def stale_index_files(wiki, expected):
    meta = os.path.join(wiki.wiki_dir, "_meta")
    if not os.path.isdir(meta):
        return []
    return [posix(os.path.join("wiki", "_meta", f)) for f in os.listdir(meta)
            if f.startswith("index-") and f.endswith(".md") and posix(os.path.join("wiki", "_meta", f)) not in expected]


def index_diff(wiki):
    expected = build_index(wiki)
    changed = [rel for rel, text in expected.items()
               if not os.path.exists(os.path.join(wiki.root, rel)) or read(os.path.join(wiki.root, rel)) != text]
    return expected, changed, stale_index_files(wiki, expected)


def cmd_index(wiki, args):
    expected, changed, stale = index_diff(wiki)
    if args.check:
        for rel in changed + stale:
            print("OUTDATED %s" % rel)
        if changed or stale:
            print("Index is out of date. Run: python3 tools/wiki.py index")
            return 1
        if not args.quiet:
            print("index is up to date")
        return 0
    for rel in changed:
        write(os.path.join(wiki.root, rel), expected[rel])
    for rel in stale:
        os.remove(os.path.join(wiki.root, rel))
    if not args.quiet:
        print("index: %d file(s) written, %d removed" % (len(changed), len(stale)) if changed or stale else "index is up to date")
    return 0


# --------------------------------------------------------------------------- search

def tokenize(text):
    return re.findall(r"[a-z0-9]+", text.lower())


def cmd_search(wiki, args):
    terms = [t for t in tokenize(args.query) if len(t) > 1]
    if not terms:
        sys.exit("error: empty query")
    docs = {}
    for p in wiki.content_pages():
        aliases = " ".join(str(a) for a in (p.get("aliases") or []))
        head = "%s %s %s %s" % (p.title, p.slug, aliases, p.get("summary") or "")
        docs[p.slug] = (p, Counter(tokenize(p.body)), set(tokenize(head)))
    n = len(docs) or 1
    df = Counter()
    for _, counts, head in docs.values():
        for t in set(terms):
            if counts[t] or t in head:
                df[t] += 1
    results = []
    for p, counts, head in docs.values():
        score, matched = 0.0, 0
        for t in terms:
            if counts[t] or t in head:
                matched += 1
                score += math.log(1 + n / (1 + df[t])) * (math.log(1 + counts[t]) + (3.0 if t in head else 0.0))
        if matched:
            results.append((score * matched / len(terms), p))
    results.sort(key=lambda r: -r[0])
    for score, p in results[: args.limit]:
        print("%6.2f  [[%s]]  %s  (%s)" % (score, p.slug, p.title, p.rel))
        if p.get("summary"):
            print("        %s" % str(p.get("summary"))[:160])
    if not results:
        print("no matches")


# --------------------------------------------------------------------------- pending raw

def norm_raw(value):
    v = posix(str(value)).strip()
    while v.startswith("../") or v.startswith("./"):
        v = v.split("/", 1)[1]
    return v


def pending_raw(wiki):
    if not os.path.isdir(wiki.raw_dir):
        return []
    sources = [p for p in wiki.pages if p.type == "source"]
    declared = set()
    for p in sources:
        raw = p.get("raw")
        for v in (raw if isinstance(raw, list) else [raw]):
            if v:
                declared.add(norm_raw(v))
    corpus = "\n".join(p.text for p in sources)
    pending = []
    for dirpath, dirnames, filenames in os.walk(wiki.raw_dir):
        rel_dir = posix(os.path.relpath(dirpath, wiki.raw_dir))
        if rel_dir.split("/")[0] == "assets":
            dirnames[:] = []
            continue
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for fn in sorted(filenames):
            if fn.startswith("."):
                continue
            rel = posix(os.path.relpath(os.path.join(dirpath, fn), wiki.root))
            if rel not in declared and fn not in corpus:
                pending.append(rel)
    return pending


def cmd_pending(wiki, args):
    files = pending_raw(wiki)
    print("\n".join(files) if files else "nothing pending")


# --------------------------------------------------------------------------- lint

def cmd_lint(wiki, args):
    errors, warnings, infos = [], [], []
    inbound = wiki.inbound()

    for slug, pages in wiki.by_slug.items():
        if len(pages) > 1:
            errors.append("duplicate slug '%s': %s" % (slug, ", ".join(p.rel for p in pages)))

    missing = defaultdict(set)
    for p in wiki.content_pages():
        if not SLUG_RE.match(p.slug):
            warnings.append("%s: file name is not kebab-case" % p.rel)
        for target in p.links:
            if not wiki.page(target):
                missing[target].add(p.slug)
        if p.fm is None:
            errors.append("%s: missing frontmatter" % p.rel)
            continue
        if p.fm.get("__invalid__"):
            errors.append("%s: unparseable frontmatter" % p.rel)
            continue
        for field in REQUIRED_FIELDS:
            if not p.get(field):
                errors.append("%s: frontmatter missing '%s'" % (p.rel, field))
        if not p.get("summary"):
            warnings.append("%s: frontmatter missing 'summary' (used by the index)" % p.rel)
        if p.type and p.type not in VALID_TYPES:
            errors.append("%s: unknown type '%s'" % (p.rel, p.type))
        if p.type == "source" and not p.get("raw"):
            warnings.append("%s: source page without 'raw:' path" % p.rel)
        if p.type in NEEDS_SOURCES and not p.source_slugs:
            warnings.append("%s: no source citations ([[src-…]])" % p.rel)
        if p.section not in ("overview", "meta") and not inbound.get(p.slug):
            warnings.append("%s: orphan (no inbound links from other pages)" % p.rel)

    for target, sources in sorted(missing.items()):
        warnings.append("missing page [[%s]] linked from %s" % (target, ", ".join(sorted(sources))))

    known, problems = discover_wikis(wiki)
    errors.extend(problems)
    for p in wiki.pages:
        for x in p.xlinks:
            wid = x.split(":", 1)[0]
            if wid not in known:
                errors.append("%s: [[%s]] refers to unknown wiki '%s'" % (p.rel, x, wid))

    log = os.path.join(wiki.wiki_dir, "log.md")
    if os.path.exists(log):
        for i, line in enumerate(read(log).splitlines(), 1):
            if line.startswith("## ") and not LOG_ENTRY_RE.match(line):
                warnings.append("wiki/log.md:%d: malformed entry header" % i)

    _, changed, stale = index_diff(wiki)
    if changed or stale:
        warnings.append("index is out of date (run: python3 tools/wiki.py index)")

    if not args.quick:
        days = int((wiki.config.get("lint") or {}).get("stale_after_days") or 180)
        for p in wiki.content_pages():
            try:
                age = (dt.date.today() - dt.date.fromisoformat(str(p.get("updated")))).days
            except ValueError:
                continue
            if age > days and p.type != "meta":
                infos.append("%s: not updated for %d days" % (p.rel, age))
            if p.get("status") == "disputed":
                infos.append("%s: status disputed" % p.rel)
        for f in pending_raw(wiki):
            infos.append("raw file not ingested: %s" % f)

    for label, items in (("ERROR", errors), ("WARN", warnings), ("INFO", infos)):
        for item in items:
            print("%-5s %s" % (label, item))
    print("\n%d errors, %d warnings, %d info (%d pages)" % (len(errors), len(warnings), len(infos), len(wiki.content_pages())))
    return 1 if errors else 0


# --------------------------------------------------------------------------- log

def cmd_log(wiki, args):
    path = os.path.join(wiki.wiki_dir, "log.md")
    if args.action and args.action[0] == "add":
        if len(args.action) != 3 or args.action[1] not in LOG_OPS:
            sys.exit("usage: wiki.py log add {%s} \"Title\" -m \"bullet\" ..." % ",".join(LOG_OPS))
        entry = "\n## [%s] %s | %s\n" % (today(), args.action[1], args.action[2])
        entry += "".join("- %s\n" % m for m in args.message or [])
        text = read(path).rstrip("\n") + "\n" + entry
        write(path, text)
        print(entry.strip())
        return 0
    if args.action:
        sys.exit("usage: wiki.py log [-n N] | log add OP TITLE -m ...")
    entries = [l for l in read(path).splitlines() if l.startswith("## [")]
    print("\n".join(entries[-args.n:]) if entries else "log is empty")
    return 0


# --------------------------------------------------------------------------- status / wikis / xlinks

def cmd_status(wiki, args):
    cfg = wiki.config
    print("%s (id: %s)%s" % (cfg.get("name", "?"), cfg.get("id", "?"), "  [TEMPLATE]" if cfg.get("template") else ""))
    if cfg.get("description"):
        print("  %s" % cfg["description"])
    types = Counter(p.type or "?" for p in wiki.content_pages())
    print("\nPages: %d  (%s)" % (sum(types.values()), ", ".join("%s %d" % kv for kv in sorted(types.items()))))
    hubs = sorted(((len(v), k) for k, v in wiki.inbound().items() if wiki.page(k)), reverse=True)[:5]
    if hubs:
        print("Hubs: %s" % ", ".join("[[%s]] (%d)" % (k, c) for c, k in hubs))
    pending = pending_raw(wiki)
    print("\nPending raw files: %d" % len(pending))
    for f in pending[:10]:
        print("  %s" % f)
    entries = [l for l in read(os.path.join(wiki.wiki_dir, "log.md")).splitlines() if l.startswith("## [")]
    print("\nRecent log:")
    for e in entries[-5:]:
        print("  %s" % e[3:])
    known, problems = discover_wikis(wiki)
    print("\nLinked wikis: %s" % (", ".join("%s%s" % (k, "" if v["available"] else " (missing)") for k, v in known.items()) or "none"))
    health = []
    _, changed, stale = index_diff(wiki)
    if changed or stale:
        health.append("index out of date → python3 tools/wiki.py index")
    if sync_plan(wiki.root)[1:] != ([], []):
        health.append("agent files out of date → python3 tools/wiki.py sync")
    if os.path.isdir(os.path.join(wiki.root, ".git")) and git(wiki.root, "config", "core.hooksPath") != ".githooks":
        health.append("git hooks not enabled → git config core.hooksPath .githooks")
    health.extend(problems)
    print("\nHealth: %s" % ("OK" if not health else ""))
    for h in health:
        print("  ! %s" % h)
    lock = os.path.join(wiki.root, ".agents", "framework.lock")
    if os.path.exists(lock):
        info = json.loads(read(lock))
        print("\nFramework: %s @ %s (%s)" % (info.get("repo"), (info.get("commit") or "?")[:10], info.get("upgraded")))
    return 0


def cmd_wikis(wiki, args):
    known, problems = discover_wikis(wiki)
    if args.json:
        print(json.dumps(known, indent=2, ensure_ascii=False))
        return 0
    if not known:
        print("no linked wikis (siblings with wiki.config.yaml are discovered automatically)")
    for wid, w in known.items():
        print("%-18s %-28s %s%s" % (wid, w.get("name", ""), posix(os.path.relpath(w["path"], wiki.root)),
                                    "" if w["available"] else "  [NOT FOUND]"))
        if w.get("scope"):
            print("%-18s scope: %s" % ("", w["scope"]))
    for p in problems:
        print("ERROR %s" % p)
    return 1 if problems else 0


def cmd_xlinks(wiki, args):
    known, problems = discover_wikis(wiki)
    status, cache, count = 0, {}, 0
    for p in wiki.pages:
        for x in p.xlinks:
            count += 1
            wid, slug = x.split(":", 1)
            w = known.get(wid)
            if not w:
                print("ERROR %s: [[%s]] unknown wiki id" % (p.rel, x))
                status = 1
            elif not w["available"]:
                print("SKIP  %s: [[%s]] wiki not available locally (%s)" % (p.rel, x, w["path"]))
            else:
                cache.setdefault(wid, Wiki(w["path"]))
                target = cache[wid].page(slug.strip())
                if target:
                    print("OK    %s: [[%s]] -> %s" % (p.rel, x, posix(os.path.relpath(target.path, wiki.root))))
                else:
                    print("ERROR %s: [[%s]] page not found in %s" % (p.rel, x, w["path"]))
                    status = 1
    for prob in problems:
        print("ERROR %s" % prob)
    print("%d cross-wiki reference(s) checked" % count)
    return 1 if status or problems else 0


# --------------------------------------------------------------------------- sync (agent files)

ACCESS = {
    "read-only": {"claude": "Read, Glob, Grep, Bash", "copilot": ["read", "search", "execute"], "codex": "read-only"},
    "write": {"claude": "Read, Write, Edit, Glob, Grep, Bash",
              "copilot": ["read", "edit", "search", "execute", "todo"], "codex": "workspace-write"},
}
GENERATED_DIRS = (".claude/agents", ".claude/skills", ".github/agents", ".codex/agents")


def parse_agent(root, path):
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", read(path), re.S)
    if not m:
        sys.exit("error: %s has no frontmatter" % path)
    meta = {}
    for line in m.group(1).splitlines():
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip().strip("\"'")
    for field in ("name", "description", "access"):
        if not meta.get(field):
            sys.exit("error: %s: missing '%s'" % (path, field))
    if meta["access"] not in ACCESS:
        sys.exit("error: %s: access must be one of %s" % (path, ", ".join(ACCESS)))
    meta["body"] = m.group(2).strip() + "\n"
    meta["source"] = posix(os.path.relpath(path, root))
    if "'''" in meta["body"]:
        sys.exit("error: %s: body must not contain '''" % path)
    return meta


def render_agent_files(a):
    t = ACCESS[a["access"]]
    note = "<!-- %s sync from %s — edit the source and re-run. -->" % (GENERATED, a["source"])
    desc = json.dumps(a["description"], ensure_ascii=False)
    return {
        ".claude/agents/%s.md" % a["name"]:
            "---\nname: %s\ndescription: %s\ntools: %s\nmodel: inherit\n---\n%s\n\n%s" % (a["name"], desc, t["claude"], note, a["body"]),
        ".github/agents/%s.agent.md" % a["name"]:
            "---\nname: %s\ndescription: %s\ntools: %s\nuser-invocable: false\n---\n%s\n\n%s"
            % (a["name"], desc, json.dumps(t["copilot"]), note, a["body"]),
        ".codex/agents/%s.toml" % a["name"]:
            "# %s\nname = %s\ndescription = %s\nsandbox_mode = %s\ndeveloper_instructions = '''\n%s'''\n"
            % (note[5:-4], json.dumps(a["name"]), desc, json.dumps(t["codex"]), a["body"]),
    }


def sync_plan(root):
    """Return (expected {rel: bytes}, changed [rel], stale [rel])."""
    files = {}
    agents_dir = os.path.join(root, ".agents", "agents")
    if os.path.isdir(agents_dir):
        for fn in sorted(os.listdir(agents_dir)):
            if fn.endswith(".md") and fn != "README.md":
                for rel, text in render_agent_files(parse_agent(root, os.path.join(agents_dir, fn))).items():
                    files[rel] = text.encode("utf-8")
    skills = os.path.join(root, ".agents", "skills")
    for dirpath, dirnames, filenames in os.walk(skills):
        dirnames[:] = [d for d in dirnames if d != "__pycache__"]
        for fn in sorted(filenames):
            src = os.path.join(dirpath, fn)
            rel = posix(os.path.join(".claude", "skills", os.path.relpath(src, skills)))
            data = open(src, "rb").read()
            if fn == "SKILL.md":
                text = data.decode("utf-8")
                note = "<!-- %s sync from %s — edit the source and re-run. -->\n" % (GENERATED, posix(os.path.relpath(src, root)))
                m = re.match(r"^(---\n.*?\n---\n)(.*)$", text, re.S)
                data = ((m.group(1) + note + m.group(2)) if m else note + text).encode("utf-8")
            files[rel] = data
    changed = [rel for rel, data in sorted(files.items())
               if not os.path.exists(os.path.join(root, rel)) or open(os.path.join(root, rel), "rb").read() != data]
    stale = []
    for sub in GENERATED_DIRS:
        for dirpath, _, filenames in os.walk(os.path.join(root, sub)):
            for fn in filenames:
                rel = posix(os.path.relpath(os.path.join(dirpath, fn), root))
                if rel in files:
                    continue
                if rel.startswith(".claude/skills/") or "GENERATED by tools/" in read(os.path.join(dirpath, fn)):
                    stale.append(rel)
    return files, changed, sorted(stale)


def do_sync(root, check=False, quiet=False):
    files, changed, stale = sync_plan(root)
    if not check:
        for rel in changed:
            path = os.path.join(root, rel)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "wb") as f:
                f.write(files[rel])
        for rel in stale:
            os.remove(os.path.join(root, rel))
        skills = os.path.join(root, ".claude", "skills")
        for dirpath, dirnames, filenames in sorted(os.walk(skills), reverse=True):
            if dirpath != skills and not os.listdir(dirpath):
                os.rmdir(dirpath)
    for rel in changed:
        print(("OUTDATED " if check else "wrote    ") + rel)
    for rel in stale:
        print(("STALE    " if check else "removed  ") + rel)
    if check and (changed or stale):
        print("Generated agent files are out of date. Run: python3 tools/wiki.py sync")
        return 1
    if not quiet and not changed and not stale:
        print("agent files are up to date")
    return 0


def cmd_sync(wiki, args):
    return do_sync(wiki.root, args.check, args.quiet)


# --------------------------------------------------------------------------- framework: manifest, upgrade, new

def read_manifest(root):
    path = os.path.join(root, "tools", "framework-manifest.txt")
    return [l.strip() for l in read(path).splitlines() if l.strip() and not l.startswith("#")]


def framework_files(root):
    """Yield framework-managed file paths (posix, relative) present under root."""
    for entry in read_manifest(root):
        full = os.path.join(root, entry)
        if entry.endswith("/"):
            for dirpath, dirnames, filenames in os.walk(full):
                dirnames[:] = sorted(d for d in dirnames if d != "__pycache__")
                for fn in sorted(filenames):
                    if not fn.endswith(".pyc") and fn != "framework.lock":
                        yield posix(os.path.relpath(os.path.join(dirpath, fn), root))
        elif os.path.exists(full):
            yield entry


def copy_framework(src, dest, dry_run=False):
    added, updated = [], []
    for rel in framework_files(src):
        s, d = os.path.join(src, rel), os.path.join(dest, rel)
        data = open(s, "rb").read()
        if os.path.exists(d) and open(d, "rb").read() == data:
            continue
        (updated if os.path.exists(d) else added).append(rel)
        if not dry_run:
            os.makedirs(os.path.dirname(d) or ".", exist_ok=True)
            shutil.copyfile(s, d)
            if rel.startswith(".githooks/") or rel.endswith(".py"):
                os.chmod(d, 0o755)
    return added, updated


def enable_hooks(root):
    if os.path.isdir(os.path.join(root, ".git")) and os.path.isdir(os.path.join(root, ".githooks")):
        git(root, "config", "core.hooksPath", ".githooks")


def cmd_upgrade(wiki, args):
    fw = wiki.config.get("framework") or {}
    if wiki.config.get("template"):
        sys.exit("error: this is the template itself; upgrade is for wikis created from it")
    tmp = None
    try:
        if args.source:
            src = os.path.abspath(args.source)
            repo, commit = src, git(src, "rev-parse", "HEAD")
        else:
            repo = fw.get("repo") or DEFAULT_FRAMEWORK_REPO
            ref = args.ref or fw.get("ref") or "main"
            tmp = tempfile.mkdtemp(prefix="llm-wiki-")
            print("Fetching %s (%s)…" % (repo, ref))
            r = subprocess.run(["git", "clone", "-q", "--depth", "1", "--branch", ref, repo, tmp],
                               capture_output=True, text=True)
            if r.returncode != 0:
                sys.exit("error: could not clone framework: %s" % r.stderr.strip())
            src, commit = tmp, git(tmp, "rev-parse", "HEAD")
        added, updated = copy_framework(src, wiki.root, args.dry_run)
        upstream = set(framework_files(src))
        local_only = [f for f in framework_files(wiki.root) if f not in upstream]
    finally:
        if tmp:
            shutil.rmtree(tmp, ignore_errors=True)
    for rel in added:
        print("added    %s" % rel)
    for rel in updated:
        print("updated  %s" % rel)
    for rel in local_only:
        print("kept     %s (local only, not in framework)" % rel)
    if args.dry_run:
        print("\n(dry run) %d to add, %d to update" % (len(added), len(updated)))
        return 0
    write(os.path.join(wiki.root, ".agents", "framework.lock"), json.dumps(
        {"repo": repo, "commit": commit, "upgraded": today()}, indent=2) + "\n")
    script = os.path.join(wiki.root, "tools", "wiki.py")
    subprocess.run([sys.executable, script, "--root", wiki.root, "sync", "--quiet"], check=False)
    subprocess.run([sys.executable, script, "--root", wiki.root, "index", "--quiet"], check=False)
    enable_hooks(wiki.root)
    print("\nFramework upgraded: %d added, %d updated. Review with `git diff`, then commit "
          "(e.g. `upgrade: framework %s`)." % (len(added), len(updated), (commit or "")[:10]))
    if added or updated:
        log_args = argparse.Namespace(action=["add", "upgrade", "Framework %s" % (commit or "")[:10]],
                                      message=["%d files added, %d updated from %s" % (len(added), len(updated), repo)], n=10)
        cmd_log(Wiki(wiki.root), log_args)
    return 0


def ask(prompt, default=None, interactive=True):
    if not interactive:
        return default
    suffix = " [%s]" % default if default else ""
    value = input("%s%s: " % (prompt, suffix)).strip()
    return value or default


def yaml_list(items, indent=4):
    items = [i for i in items if i]
    if not items:
        return " " * indent + '- ""'
    return "\n".join(" " * indent + "- " + json.dumps(i, ensure_ascii=False) for i in items)


def render_skeleton(src, dest, values):
    skel = os.path.join(src, "templates", "skeleton")
    for dirpath, _, filenames in os.walk(skel):
        for fn in filenames:
            s = os.path.join(dirpath, fn)
            text = read(s)
            for k, v in values.items():
                text = text.replace("{{%s}}" % k, v)
            write(os.path.join(dest, os.path.relpath(s, skel)), text)
    for cat in DEFAULT_CATEGORIES:
        write(os.path.join(dest, "wiki", cat, ".gitkeep"), "")
    write(os.path.join(dest, "raw", "assets", ".gitkeep"), "")


def create_wiki(src, dest, args, in_place=False):
    interactive = sys.stdin.isatty() and not args.yes
    default_id = re.sub(r"[^a-z0-9]+", "-", os.path.basename(os.path.abspath(dest)).lower()).strip("-")
    default_id = re.sub(r"-?wiki$", "", default_id) or default_id
    wid = args.id or ask("Wiki id (kebab-case, unique)", default_id, interactive)
    if not wid or not SLUG_RE.match(wid):
        sys.exit("error: wiki id must be kebab-case (got %r)" % wid)
    name = args.name or ask("Wiki name", wid.replace("-", " ").title() + " Wiki", interactive)
    desc = args.description or ask("One-line description", "Knowledge base about %s." % name, interactive)
    scope_in = args.scope_in or [s.strip() for s in (ask("In scope (comma-separated)", "", interactive) or "").split(",")]
    scope_out = args.scope_out or [s.strip() for s in (ask("Out of scope (comma-separated)", "", interactive) or "").split(",")]
    src_cfg = load_config(src)
    values = {
        "ID": wid, "NAME": name, "DESCRIPTION": json.dumps(desc, ensure_ascii=False), "DATE": today(),
        "SCOPE_IN": yaml_list(scope_in), "SCOPE_OUT": yaml_list(scope_out),
        "FRAMEWORK_REPO": str((src_cfg.get("framework") or {}).get("repo") or DEFAULT_FRAMEWORK_REPO),
    }
    if not in_place:
        copy_framework(src, dest)
    else:
        for path in ("tests",):
            shutil.rmtree(os.path.join(dest, path), ignore_errors=True)
        for stale in ("wiki/_meta/external-links.md",):
            if os.path.exists(os.path.join(dest, stale)):
                os.remove(os.path.join(dest, stale))
    render_skeleton(src, dest, values)
    do_sync(dest, quiet=True)
    cmd_index(Wiki(dest), argparse.Namespace(check=False, quiet=True))
    if not args.no_git and shutil.which("git"):
        if not os.path.isdir(os.path.join(dest, ".git")):
            git(dest, "init", "-q", "-b", "main") is not None or git(dest, "init", "-q")
        enable_hooks(dest)
        git(dest, "add", "-A")
        subprocess.run(["git", "-C", dest, "commit", "-q", "--no-verify", "-m",
                        "setup: %s created from llm-wiki framework" % name], check=False)
    print("Created wiki '%s' (id: %s) in %s" % (name, wid, dest))
    if args.github:
        if not shutil.which("gh"):
            print("warning: GitHub CLI (gh) not found — create the repo manually and push.")
        else:
            vis = "--public" if args.public else "--private"
            r = subprocess.run(["gh", "repo", "create", args.github, vis, "--source", dest, "--push"])
            if r.returncode == 0:
                print("Pushed to GitHub: %s" % args.github)
    print("Next: open it with your agent (Copilot, Codex, Claude Code) and run setup-wiki, "
          "then drop sources into raw/ and run ingest.")
    return 0


def cmd_new(wiki, args):
    dest = os.path.abspath(args.target)
    if os.path.exists(dest) and os.listdir(dest):
        sys.exit("error: %s exists and is not empty" % dest)
    return create_wiki(wiki.root, dest, args)


def cmd_init(wiki, args):
    if not wiki.config.get("template"):
        sys.exit("error: this repo is already a wiki (wiki.config.yaml has no 'template: true')")
    return create_wiki(wiki.root, wiki.root, args, in_place=True)


# --------------------------------------------------------------------------- main

def add_create_args(p):
    p.add_argument("--id")
    p.add_argument("--name")
    p.add_argument("--description")
    p.add_argument("--scope-in", action="append", help="repeatable")
    p.add_argument("--scope-out", action="append", help="repeatable")
    p.add_argument("--github", metavar="OWNER/REPO", help="create the GitHub repo with gh and push")
    p.add_argument("--public", action="store_true", help="with --github: public repo (default private)")
    p.add_argument("--no-git", action="store_true", help="don't initialize git")
    p.add_argument("-y", "--yes", action="store_true", help="non-interactive: use defaults for missing values")


def main(argv=None):
    parser = argparse.ArgumentParser(prog="wiki.py", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=DEFAULT_ROOT, help="wiki root (default: this repo)")
    sub = parser.add_subparsers(dest="cmd")
    sub.add_parser("status")
    s = sub.add_parser("search")
    s.add_argument("query")
    s.add_argument("--limit", type=int, default=10)
    for name in ("index", "sync"):
        p = sub.add_parser(name)
        p.add_argument("--check", action="store_true")
        p.add_argument("--quiet", action="store_true")
    p = sub.add_parser("lint")
    p.add_argument("--quick", action="store_true", help="skip stale/pending checks")
    sub.add_parser("pending")
    p = sub.add_parser("log")
    p.add_argument("action", nargs="*", help="empty to show, or: add OP TITLE")
    p.add_argument("-m", "--message", action="append", help="bullet line (repeatable)")
    p.add_argument("-n", type=int, default=10)
    p = sub.add_parser("wikis")
    p.add_argument("--json", action="store_true")
    sub.add_parser("xlinks")
    p = sub.add_parser("upgrade")
    p.add_argument("--from", dest="source", metavar="PATH", help="local framework checkout instead of git clone")
    p.add_argument("--ref", help="branch or tag (default: framework.ref or main)")
    p.add_argument("--dry-run", action="store_true")
    p = sub.add_parser("new")
    p.add_argument("target")
    add_create_args(p)
    p = sub.add_parser("init")
    add_create_args(p)

    args = parser.parse_args(argv)
    if not args.cmd:
        parser.print_help()
        return 0
    if args.cmd == "sync":
        return do_sync(os.path.abspath(args.root), args.check, args.quiet)
    handlers = {"status": cmd_status, "search": cmd_search, "index": cmd_index, "lint": cmd_lint,
                "pending": cmd_pending, "log": cmd_log, "wikis": cmd_wikis, "xlinks": cmd_xlinks,
                "upgrade": cmd_upgrade, "new": cmd_new, "init": cmd_init}
    return handlers[args.cmd](Wiki(args.root), args) or 0


if __name__ == "__main__":
    sys.exit(main())
